apiVersion: v1
kind: Pod
spec:
  containers:
    - name: akane
      image: ghcr.io/ikanago/akane.go@sha256:0e78b6e1f66a1040cc88cb55f8cc01f1efa540bcfd91d6ac26dbf4b224ec2a8c
      envFrom:
        - secretRef:
            name: akane-secret-volume
