apiVersion: v1
kind: Pod
metadata:
  name: akane
spec:
  containers:
    - name: akane
      image: ghcr.io/ikanago/akane.go@sha256:ebade99fb643a350287e252e3c0e9b371c07f9538729efca05c57eddd95a8d8a
      envFrom:
        - secretRef:
            name: akane-secret
  nodeSelector:
    nodetype: agent
