apiVersion: v1
kind: Pod
metadata:
  name: akane
spec:
  containers:
    - name: akane
      image: ghcr.io/ikanago/akane.go@sha256:7c590c00c515cdaa03df2731fe48115a58915bc77c9305508dfcff46be44cfea
      envFrom:
        - secretRef:
            name: akane-secret
  nodeSelector:
    nodetype: agent
